
translator: translator.c cstring.c parser.c writer.c helper.c arithmetic.c push.c pop.c function.c return.c
	gcc translator.c cstring.c parser.c writer.c helper.c arithmetic.c push.c pop.c function.c return.c 
