
translator: translator.c cstring.c parser.c writer.c helper.c arithmetic.c push.c pop.c function.c return.c call.c goto.c
	gcc translator.c cstring.c parser.c writer.c helper.c arithmetic.c push.c pop.c function.c return.c call.c goto.c ../common/{code_reader.c,file_handler.c,file_reader.c,file_content.c}
